"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-02 14:29:38.076014
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shops",
        sa.Column("shop_domain", sa.String(length=255), nullable=False),
        sa.Column("access_token_enc", sa.LargeBinary(), nullable=True),
        sa.Column("access_token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("refresh_token_enc", sa.LargeBinary(), nullable=True),
        sa.Column("refresh_token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scopes", sa.Text(), nullable=True),
        sa.Column("installed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("uninstalled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("automation_enabled", sa.Boolean(), nullable=False),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shops")),
        sa.UniqueConstraint("shop_domain", name=op.f("uq_shops_shop_domain")),
    )
    op.create_table(
        "webhook_events",
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column("topic", sa.String(length=100), nullable=False),
        sa.Column("external_event_id", sa.String(length=255), nullable=False),
        sa.Column("shop_domain", sa.String(length=255), nullable=True),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("headers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processing_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "processing_status",
            sa.Enum(
                "RECEIVED",
                "PROCESSING",
                "PROCESSED",
                "FAILED",
                "IGNORED",
                name="webhookstatus",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook_events")),
        sa.UniqueConstraint(
            "source", "external_event_id", name=op.f("uq_webhook_events_source_external_event_id")
        ),
    )
    op.create_index(
        op.f("ix_webhook_events_processing_status_received_at"),
        "webhook_events",
        ["processing_status", "received_at"],
        unique=False,
    )
    op.create_table(
        "allocation_rules",
        sa.Column("shop_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("conditions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "strategy",
            sa.Enum(
                "FASTEST",
                "CHEAPEST",
                "BALANCED",
                "PRIORITY",
                "CUSTOM",
                name="allocationstrategy",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"],
            ["shops.id"],
            name=op.f("fk_allocation_rules_shop_id_shops"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_allocation_rules")),
    )
    op.create_index(
        op.f("ix_allocation_rules_shop_id_is_active_priority"),
        "allocation_rules",
        ["shop_id", "is_active", "priority"],
        unique=False,
    )
    op.create_table(
        "carrier_accounts",
        sa.Column("shop_id", sa.BigInteger(), nullable=False),
        sa.Column("carrier_code", sa.String(length=40), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column(
            "environment",
            sa.Enum(
                "MOCK",
                "SANDBOX",
                "PRODUCTION",
                name="carrierenvironment",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("credentials_enc", sa.LargeBinary(), nullable=True),
        sa.Column("credentials_hint", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("webhook_token", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"],
            ["shops.id"],
            name=op.f("fk_carrier_accounts_shop_id_shops"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_carrier_accounts")),
        sa.UniqueConstraint(
            "shop_id",
            "carrier_code",
            "environment",
            "label",
            name=op.f("uq_carrier_accounts_shop_id_carrier_code_environment_label"),
        ),
        sa.UniqueConstraint("webhook_token", name=op.f("uq_carrier_accounts_webhook_token")),
    )
    op.create_table(
        "shopify_orders",
        sa.Column("shop_id", sa.BigInteger(), nullable=False),
        sa.Column("shopify_order_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("customer_name", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("shipping_address", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "payment_mode",
            sa.Enum("COD", "PREPAID", "UNKNOWN", name="paymentmode", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("payment_gateways", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("total_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("outstanding_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("tags", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("financial_status", sa.String(length=40), nullable=True),
        sa.Column("fulfillment_status", sa.String(length=40), nullable=True),
        sa.Column("risk_level", sa.String(length=20), nullable=True),
        sa.Column("risk_recommendation", sa.String(length=20), nullable=True),
        sa.Column("shopify_created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("automation_disabled", sa.Boolean(), nullable=False),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"],
            ["shops.id"],
            name=op.f("fk_shopify_orders_shop_id_shops"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shopify_orders")),
        sa.UniqueConstraint(
            "shop_id", "shopify_order_id", name=op.f("uq_shopify_orders_shop_id_shopify_order_id")
        ),
    )
    op.create_table(
        "warehouses",
        sa.Column("shop_id", sa.BigInteger(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("contact_name", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=32), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("address1", sa.String(length=255), nullable=False),
        sa.Column("address2", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("state", sa.String(length=100), nullable=False),
        sa.Column("pincode", sa.String(length=16), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("shopify_location_id", sa.String(length=64), nullable=True),
        sa.Column("default_package", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"], ["shops.id"], name=op.f("fk_warehouses_shop_id_shops"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_warehouses")),
        sa.UniqueConstraint("shop_id", "code", name=op.f("uq_warehouses_shop_id_code")),
        sa.UniqueConstraint(
            "shop_id", "shopify_location_id", name=op.f("uq_warehouses_shop_id_shopify_location_id")
        ),
    )
    op.create_table(
        "carrier_settings",
        sa.Column("shop_id", sa.BigInteger(), nullable=False),
        sa.Column("carrier_code", sa.String(length=40), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("cod_enabled", sa.Boolean(), nullable=False),
        sa.Column("prepaid_enabled", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("max_shipping_cost", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("min_weight_g", sa.Integer(), nullable=True),
        sa.Column("max_weight_g", sa.Integer(), nullable=True),
        sa.Column("performance_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("active_account_id", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["active_account_id"],
            ["carrier_accounts.id"],
            name=op.f("fk_carrier_settings_active_account_id_carrier_accounts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"],
            ["shops.id"],
            name=op.f("fk_carrier_settings_shop_id_shops"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_carrier_settings")),
        sa.UniqueConstraint(
            "shop_id", "carrier_code", name=op.f("uq_carrier_settings_shop_id_carrier_code")
        ),
    )
    op.create_table(
        "carrier_warehouse_mappings",
        sa.Column("carrier_account_id", sa.BigInteger(), nullable=False),
        sa.Column("warehouse_id", sa.BigInteger(), nullable=False),
        sa.Column("carrier_warehouse_ref", sa.String(length=255), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["carrier_account_id"],
            ["carrier_accounts.id"],
            name=op.f("fk_carrier_warehouse_mappings_carrier_account_id_carrier_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_carrier_warehouse_mappings_warehouse_id_warehouses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_carrier_warehouse_mappings")),
        sa.UniqueConstraint(
            "carrier_account_id",
            "warehouse_id",
            name=op.f("uq_carrier_warehouse_mappings_carrier_account_id_warehouse_id"),
        ),
    )
    op.create_table(
        "shopify_fulfillment_orders",
        sa.Column("shop_id", sa.BigInteger(), nullable=False),
        sa.Column("order_id", sa.BigInteger(), nullable=False),
        sa.Column("shopify_fulfillment_order_id", sa.String(length=64), nullable=False),
        sa.Column("shopify_location_id", sa.String(length=64), nullable=True),
        sa.Column("warehouse_id", sa.BigInteger(), nullable=True),
        sa.Column("shopify_status", sa.String(length=40), nullable=False),
        sa.Column("request_status", sa.String(length=40), nullable=True),
        sa.Column("delivery_method", sa.String(length=40), nullable=True),
        sa.Column("hold_reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("line_items", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("weight_g", sa.Integer(), nullable=True),
        sa.Column(
            "logistics_status",
            sa.Enum(
                "RECEIVED",
                "SETTLING",
                "MANUAL_REVIEW",
                "AWAITING_ALLOCATION",
                "ALLOCATING",
                "ALLOCATED",
                "NO_CARRIER_AVAILABLE",
                "SHIPMENT_PENDING",
                "RECONCILING",
                "SHIPPED",
                "FAILED",
                "SKIPPED",
                "AUTOMATION_DISABLED",
                "CANCELLED",
                name="logisticsstatus",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("status_reason", sa.String(length=64), nullable=True),
        sa.Column("status_detail", sa.Text(), nullable=True),
        sa.Column("next_check_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hold_last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hold_released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_override_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_override_by", sa.String(length=255), nullable=True),
        sa.Column("last_evaluated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["shopify_orders.id"],
            name=op.f("fk_shopify_fulfillment_orders_order_id_shopify_orders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"],
            ["shops.id"],
            name=op.f("fk_shopify_fulfillment_orders_shop_id_shops"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_shopify_fulfillment_orders_warehouse_id_warehouses"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shopify_fulfillment_orders")),
        sa.UniqueConstraint(
            "shopify_fulfillment_order_id",
            name=op.f("uq_shopify_fulfillment_orders_shopify_fulfillment_order_id"),
        ),
    )
    op.create_index(
        op.f("ix_shopify_fulfillment_orders_logistics_status_next_check_at"),
        "shopify_fulfillment_orders",
        ["logistics_status", "next_check_at"],
        unique=False,
    )
    op.create_table(
        "carrier_serviceability_checks",
        sa.Column("shop_id", sa.BigInteger(), nullable=False),
        sa.Column("fulfillment_order_id", sa.BigInteger(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("carrier_code", sa.String(length=40), nullable=False),
        sa.Column("request", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("serviceable", sa.Boolean(), nullable=True),
        sa.Column("cod_available", sa.Boolean(), nullable=True),
        sa.Column("prepaid_available", sa.Boolean(), nullable=True),
        sa.Column("pickup_available", sa.Boolean(), nullable=True),
        sa.Column("response", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_class", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.ForeignKeyConstraint(
            ["fulfillment_order_id"],
            ["shopify_fulfillment_orders.id"],
            name=op.f(
                "fk_carrier_serviceability_checks_fulfillment_order_id_shopify_fulfillment_orders"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"],
            ["shops.id"],
            name=op.f("fk_carrier_serviceability_checks_shop_id_shops"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_carrier_serviceability_checks")),
    )
    op.create_index(
        op.f("ix_carrier_serviceability_checks_fulfillment_order_id_created_at"),
        "carrier_serviceability_checks",
        ["fulfillment_order_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "shipments",
        sa.Column("shop_id", sa.BigInteger(), nullable=False),
        sa.Column("order_id", sa.BigInteger(), nullable=False),
        sa.Column("fulfillment_order_id", sa.BigInteger(), nullable=False),
        sa.Column("shopify_order_id", sa.String(length=64), nullable=False),
        sa.Column("shopify_order_name", sa.String(length=64), nullable=False),
        sa.Column("shopify_fulfillment_order_id", sa.String(length=64), nullable=False),
        sa.Column("carrier_code", sa.String(length=40), nullable=False),
        sa.Column("carrier_account_id", sa.BigInteger(), nullable=True),
        sa.Column("warehouse_id", sa.BigInteger(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("carrier_shipment_id", sa.String(length=128), nullable=True),
        sa.Column("awb", sa.String(length=64), nullable=True),
        sa.Column("tracking_url", sa.Text(), nullable=True),
        sa.Column("label_url", sa.Text(), nullable=True),
        sa.Column("shipping_cost", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("estimated_delivery_date", sa.Date(), nullable=True),
        sa.Column("cod_amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("declared_value", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("weight_g", sa.Integer(), nullable=True),
        sa.Column("dimensions", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "CREATING",
                "CREATION_UNKNOWN",
                "CREATE_FAILED",
                "AWB_CREATED",
                "PICKUP_SCHEDULED",
                "PICKED_UP",
                "IN_TRANSIT",
                "OUT_FOR_DELIVERY",
                "DELIVERED",
                "DELIVERY_FAILED",
                "RTO_INITIATED",
                "RTO_IN_TRANSIT",
                "RTO_DELIVERED",
                "CANCEL_REQUESTED",
                "CANCELLED",
                "EXCEPTION",
                name="shipmentstatus",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("raw_create_response", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("shopify_fulfillment_id", sa.String(length=64), nullable=True),
        sa.Column(
            "shopify_sync_status",
            sa.Enum(
                "PENDING",
                "SYNCED",
                "FAILED",
                name="shopifysyncstatus",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("shopify_sync_error", sa.Text(), nullable=True),
        sa.Column("last_tracking_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_poll_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_reason", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["carrier_account_id"],
            ["carrier_accounts.id"],
            name=op.f("fk_shipments_carrier_account_id_carrier_accounts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["fulfillment_order_id"],
            ["shopify_fulfillment_orders.id"],
            name=op.f("fk_shipments_fulfillment_order_id_shopify_fulfillment_orders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["shopify_orders.id"],
            name=op.f("fk_shipments_order_id_shopify_orders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"], ["shops.id"], name=op.f("fk_shipments_shop_id_shops"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_shipments_warehouse_id_warehouses"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shipments")),
        sa.UniqueConstraint("carrier_code", "awb", name=op.f("uq_shipments_carrier_code_awb")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_shipments_idempotency_key")),
    )
    op.create_index(op.f("ix_shipments_next_poll_at"), "shipments", ["next_poll_at"], unique=False)
    op.create_index(
        op.f("ix_shipments_shop_id_status"), "shipments", ["shop_id", "status"], unique=False
    )
    op.create_index(
        "uq_shipments_active_fulfillment_order",
        "shipments",
        ["shopify_fulfillment_order_id"],
        unique=True,
        postgresql_where=sa.text("status NOT IN ('CANCELLED', 'CREATE_FAILED')"),
    )
    op.create_table(
        "automation_logs",
        sa.Column("shop_id", sa.BigInteger(), nullable=False),
        sa.Column("order_id", sa.BigInteger(), nullable=True),
        sa.Column("fulfillment_order_id", sa.BigInteger(), nullable=True),
        sa.Column("shipment_id", sa.BigInteger(), nullable=True),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("step", sa.String(length=64), nullable=False),
        sa.Column(
            "level",
            sa.Enum("INFO", "WARNING", "ERROR", name="loglevel", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("actor", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.ForeignKeyConstraint(
            ["fulfillment_order_id"],
            ["shopify_fulfillment_orders.id"],
            name=op.f("fk_automation_logs_fulfillment_order_id_shopify_fulfillment_orders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["shopify_orders.id"],
            name=op.f("fk_automation_logs_order_id_shopify_orders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["shipment_id"],
            ["shipments.id"],
            name=op.f("fk_automation_logs_shipment_id_shipments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"],
            ["shops.id"],
            name=op.f("fk_automation_logs_shop_id_shops"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_automation_logs")),
    )
    op.create_index(
        op.f("ix_automation_logs_order_id_created_at"),
        "automation_logs",
        ["order_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_automation_logs_shop_id_created_at"),
        "automation_logs",
        ["shop_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "carrier_quotes",
        sa.Column("check_id", sa.BigInteger(), nullable=True),
        sa.Column("fulfillment_order_id", sa.BigInteger(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("carrier_code", sa.String(length=40), nullable=False),
        sa.Column("cost", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("transit_days", sa.Integer(), nullable=True),
        sa.Column("edd", sa.Date(), nullable=True),
        sa.Column("score", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.Column("eligible", sa.Boolean(), nullable=False),
        sa.Column("rejection_reason", sa.String(length=64), nullable=True),
        sa.Column("rejection_detail", sa.Text(), nullable=True),
        sa.Column("selected", sa.Boolean(), nullable=False),
        sa.Column("strategy", sa.String(length=20), nullable=False),
        sa.Column("rule_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.ForeignKeyConstraint(
            ["check_id"],
            ["carrier_serviceability_checks.id"],
            name=op.f("fk_carrier_quotes_check_id_carrier_serviceability_checks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["fulfillment_order_id"],
            ["shopify_fulfillment_orders.id"],
            name=op.f("fk_carrier_quotes_fulfillment_order_id_shopify_fulfillment_orders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["allocation_rules.id"],
            name=op.f("fk_carrier_quotes_rule_id_allocation_rules"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_carrier_quotes")),
    )
    op.create_index(
        op.f("ix_carrier_quotes_fulfillment_order_id_run_id"),
        "carrier_quotes",
        ["fulfillment_order_id", "run_id"],
        unique=False,
    )
    op.create_table(
        "tracking_events",
        sa.Column("shipment_id", sa.BigInteger(), nullable=False),
        sa.Column("carrier_code", sa.String(length=40), nullable=False),
        sa.Column("awb", sa.String(length=64), nullable=False),
        sa.Column("raw_status", sa.String(length=128), nullable=False),
        sa.Column(
            "normalized_status",
            sa.Enum(
                "AWB_CREATED",
                "PICKUP_SCHEDULED",
                "PICKED_UP",
                "IN_TRANSIT",
                "OUT_FOR_DELIVERY",
                "DELIVERED",
                "DELIVERY_FAILED",
                "RTO_INITIATED",
                "RTO_IN_TRANSIT",
                "RTO_DELIVERED",
                "CANCELLED",
                "EXCEPTION",
                name="trackingstatus",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "WEBHOOK", "POLL", "MANUAL", name="trackingsource", native_enum=False, length=40
            ),
            nullable=False,
        ),
        sa.Column("dedup_hash", sa.String(length=64), nullable=False),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("shopify_pushed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.ForeignKeyConstraint(
            ["shipment_id"],
            ["shipments.id"],
            name=op.f("fk_tracking_events_shipment_id_shipments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tracking_events")),
        sa.UniqueConstraint(
            "shipment_id", "dedup_hash", name=op.f("uq_tracking_events_shipment_id_dedup_hash")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tracking_events")
    op.drop_index(
        op.f("ix_carrier_quotes_fulfillment_order_id_run_id"), table_name="carrier_quotes"
    )
    op.drop_table("carrier_quotes")
    op.drop_index(op.f("ix_automation_logs_shop_id_created_at"), table_name="automation_logs")
    op.drop_index(op.f("ix_automation_logs_order_id_created_at"), table_name="automation_logs")
    op.drop_table("automation_logs")
    op.drop_index(
        "uq_shipments_active_fulfillment_order",
        table_name="shipments",
        postgresql_where=sa.text("status NOT IN ('CANCELLED', 'CREATE_FAILED')"),
    )
    op.drop_index(op.f("ix_shipments_shop_id_status"), table_name="shipments")
    op.drop_index(op.f("ix_shipments_next_poll_at"), table_name="shipments")
    op.drop_table("shipments")
    op.drop_index(
        op.f("ix_carrier_serviceability_checks_fulfillment_order_id_created_at"),
        table_name="carrier_serviceability_checks",
    )
    op.drop_table("carrier_serviceability_checks")
    op.drop_index(
        op.f("ix_shopify_fulfillment_orders_logistics_status_next_check_at"),
        table_name="shopify_fulfillment_orders",
    )
    op.drop_table("shopify_fulfillment_orders")
    op.drop_table("carrier_warehouse_mappings")
    op.drop_table("carrier_settings")
    op.drop_table("warehouses")
    op.drop_table("shopify_orders")
    op.drop_table("carrier_accounts")
    op.drop_index(
        op.f("ix_allocation_rules_shop_id_is_active_priority"), table_name="allocation_rules"
    )
    op.drop_table("allocation_rules")
    op.drop_index(
        op.f("ix_webhook_events_processing_status_received_at"), table_name="webhook_events"
    )
    op.drop_table("webhook_events")
    op.drop_table("shops")
    # ### end Alembic commands ###
