"""allocation and tracking fields

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-02 15:12:59.115290
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "shipments",
        sa.Column("reconcile_attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
    )
    op.add_column(
        "shopify_fulfillment_orders",
        sa.Column("selected_carrier_code", sa.String(length=40), nullable=True),
    )
    op.add_column(
        "shopify_fulfillment_orders",
        sa.Column("forced_carrier_code", sa.String(length=40), nullable=True),
    )
    op.add_column(
        "shopify_fulfillment_orders", sa.Column("selected_by", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "shopify_fulfillment_orders", sa.Column("allocation_run_id", sa.Uuid(), nullable=True)
    )
    op.add_column(
        "shopify_fulfillment_orders",
        sa.Column(
            "allocation_ranking",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "tracking_events",
        sa.Column("applied", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tracking_events", "applied")
    op.drop_column("shopify_fulfillment_orders", "allocation_ranking")
    op.drop_column("shopify_fulfillment_orders", "allocation_run_id")
    op.drop_column("shopify_fulfillment_orders", "selected_by")
    op.drop_column("shopify_fulfillment_orders", "forced_carrier_code")
    op.drop_column("shopify_fulfillment_orders", "selected_carrier_code")
    op.drop_column("shipments", "reconcile_attempts")
    # ### end Alembic commands ###
